env:
  browser: true
  node: true
  es6: true

parserOptions:
  ecmaVersion: 2018
  ecmaFeatures:
    impliedStrict: true
    jsx: true
  sourceType: 'module'

plugins:
  - 'react'
  - 'react-hooks'

extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react/jsx-runtime'
  - 'plugin:react-hooks/recommended'
  - 'plugin:jsx-a11y/strict'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'

rules:
  no-console: error
  no-alert: error
  no-caller: error
  no-eval: error
  no-implied-eval: error
  no-var: error
  prefer-const: error
  sort-imports:
    - error
    - ignoreDeclarationSort: true
  import/order:
    - error
    - groups:
        - - builtin
          - external
        - internal
        - parent
        - - sibling
          - index
        - - unknown
          - object
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  import/newline-after-import: error
  eqeqeq: error
  no-param-reassign: error

ignorePatterns:
  - /.cache
  - /node_modules
  - /public

settings:
  react:
    version: "detect"
